config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "properties#index"
  resources :properties do
    collection do
      get 'search'
    end
    resources :rooms, only: [:index, :create, :show, :destroy, :edit, :update] do
      resources :approaches, only: [:index, :create, :destroy]
    end
  end

  resources :items do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approach.rb
class Approach < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/construction_time.rb
class ConstructionTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '0.5' },
    { id: 3, name: '1.0' },
    { id: 4, name: '1.5' },
    { id: 5, name: '2.0' },
    { id: 6, name: '2.5' },
    { id: 7, name: '3.0' },
    { id: 8, name: '3.5' },
    { id: 9, name: '4.0' },
    { id: 10, name: '4.5' },
    { id: 11, name: '5.0' },
    { id: 12, name: '5.5' },
    { id: 13, name: '6.0' },
    { id: 14, name: '終日' }
  ]

  include ActiveHash::Associations
  has_many :rooms

end

app/models/gas.rb
class Gas < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '都市ガス' },
    { id: 3, name: 'プロパン' }
  ]

  include ActiveHash::Associations
  has_many :properties
  has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord

  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gas
  

  def self.search(search)
    if search != ""
      Item.where('product_number LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

end

app/models/parking.rb
class Parking < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '近くコインP' },
    { id: 3, name: '路駐' },
    { id: 4, name: 'なし' }
  ]

  include ActiveHash::Associations
  has_many :properties

  end

app/models/property.rb
class Property < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :parking
  belongs_to :gas
  belongs_to :propertyKind
  
  validates :property_name, presence: true

  def self.search(search)
    if search != ""
      Property.where('property_name LIKE(?)', "%#{search}%")
    else
      Property.all
    end
  end

end

app/models/property_kind.rb
class PropertyKind < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'マンション' },
    { id: 3, name: 'アパート' },
    { id: 4, name: '戸建て' },
    { id: 5, name: '店舗等・その他'}
  ]

  include ActiveHash::Associations
  has_many :properties

end
  

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :property
  has_many :approaches, dependent: :destroy
  has_many_attached :images

  validates :room_number, presence: true
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :construction_time
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :approaches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
  end

  def new
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/approaches_controller.rb
class ApproachesController < ApplicationController

  def index
    @approach = Approach.new
    @room = Room.find(params[:room_id])
    @property = Property.find(params[:property_id]) 
  end

  def create
    @room = Room.find(params[:room_id])
    @approach = Approach.create(approach_params)
    if @approach.save
      redirect_to property_room_path(@room.property_id, @room.id)
    else
      render action: :index
    end
  end

  def destroy
    @property = Property.find(params[:property_id])
    @room = Room.find(params[:room_id])
    approach = Approach.find(params[:id])
    approach.destroy
    redirect_to property_room_path(@property.id, @room.id)
  end 

  private
  def approach_params
    params.require(:approach).permit(:content) .merge(room_id: params[:room_id], user_id: current_user.id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
      if @item.save
        redirect_to root_path
      else
        render :new
      end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def search
    @items = Item.search(params[:keyword])
  end


  private
  def item_params
    params.require(:item).permit(:item_name, :product_number, :price,
       :rate, :gas_id, :supplier, :maker, images: [])
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
      if @property.save
        redirect_to property_path(@property.id)
      else
        render :new
      end
  end

  def show
    @property = Property.find(params[:id])
    @rooms = Room.where(property_id: params[:id])
  end

  def destroy
    property = Property.find(params[:id])
    property.destroy
    redirect_to root_path
  end

  def search
    @properties = Property.search(params[:keyword])
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to property_path
    else
      render :edit
    end
  end

  private
  def property_params
    params.require(:property).permit(:property_name, :address, :existing_information,
      :property_kind_id, :remarks, :parking_id, :gas_id, images: [])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @room = Room.new
    @property = Property.find(params[:property_id])
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to property_room_path(@room.property_id, @room.id)
    else
      redirect_to property_rooms_path(@room.property_id)
    end
  end

  def show
    @room = Room.find(params[:id])
    @property = Property.find(params[:property_id])
    @approaches = Approach.where(id: params[:id])
    @approach = Approach.where(room_id: params[:id]) 
  end

  def destroy
    @property = Property.find(params[:property_id])
    room = Room.find(params[:id])
    room.destroy
    redirect_to property_path(@property.id)
  end 

  def edit
    @property = Property.find(params[:property_id])
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to property_room_path(@room.property_id,@room.id)
    else
      render :edit
    end
  end

  private
  def room_params
    params.require(:room).permit(:room_number, :construction_time_id, :instruction, :remarks_room, :construction_detail, 
      :existing_information, :existing_maker, :construction_day, images: []).merge(property_id: params[:property_id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approaches_helper.rb
module ApproachesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/approaches/index.html.erb
<div class="contents">
  <div class="container">
    <%= form_with(model: [@property, @room, @approach],  local: true) do |form| %>
    <div class="input-form">
      <div class="remarks_room form">
        <div class="weight-bold-text">アプローチ</div>
          <%= form.text_area :content, placeholder: "アプローチ", rows: "10", size: "53x10" %>
        </div>
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<div class="contents">
  <div class="container">
    <h3>商品登録</h3>
    <%= form_with(model: @item, local: true) do |form| %>
    <div class="input-form">
    <div class="weight-bold-text">画像</div>
      <div class="item-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
      <div class="item_name form">
        <div class="weight-bold-text">商品名</div>
        <%= form.text_field :item_name, placeholder: "商品名" %>
      </div>
      <div class="maker form">
        <div class="weight-bold-text">メーカー</div>
        <%= form.text_field :maker, placeholder: "メーカー" %>
      </div>
      <div class="product_number form">
        <div class="weight-bold-text">品番</div>
        <%= form.text_field :product_number, placeholder: "品番" %>
      </div>
      <div class="price form">
        <div class="weight-bold-text">定価</div>
        <%= form.text_field :price, placeholder: "定価" %>
      </div>
      <div class="rate form">
        <div class="weight-bold-text">仕切り</div>
        <%= form.text_field :rate, placeholder: "仕切り" %>
      </div>
      <div class="gas form">
        <div class="weight-bold-text">ガス種</div>
        <%= form.collection_select(:gas_id, Gas.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="supplier form">
        <div class="weight-bold-text">仕入れ先</div>
        <%= form.text_field :supplier, placeholder: "品番" %>
      </div>
  
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="contents">
  <div class="search">
    <h3>商品を検索する</h3>
    <%= form_with url: search_items_path, local: true, method: :get do |form| %>
      <%= form.text_field :keyword, placeholder: "品番" %>
      <%= form.submit "検索" %>
    <% end %>
  </div>

  <div class="record-item">
    <h3>登録した商品</h3>
    <div class="item-lists">
        <% @items.each do |item| %>
          <div class="item-list">
            
            <%= link_to item.product_number, item_path(item.id),class:"menuLIST" %>
            <%= item.maker %>
            <%= item.item_name %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="contents">
  <div class="container">
    <h3>商品登録</h3>
    <%= form_with(model: @item, local: true) do |form| %>
    <div class="input-form">
    <div class="weight-bold-text">画像</div>
      <div class="item-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
      <div class="item_name form">
        <div class="weight-bold-text">商品名</div>
        <%= form.text_field :item_name, placeholder: "商品名" %>
      </div>
      <div class="maker form">
        <div class="weight-bold-text">メーカー</div>
        <%= form.text_field :maker, placeholder: "メーカー" %>
      </div>
      <div class="product_number form">
        <div class="weight-bold-text">品番</div>
        <%= form.text_field :product_number, placeholder: "品番" %>
      </div>
      <div class="price form">
        <div class="weight-bold-text">定価</div>
        <%= form.text_field :price, placeholder: "定価" %>
      </div>
      <div class="rate form">
        <div class="weight-bold-text">仕切り</div>
        <%= form.text_field :rate, placeholder: "仕切り" %>
      </div>
      <div class="gas form">
        <div class="weight-bold-text">ガス種</div>
        <%= form.collection_select(:gas_id, Gas.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="supplier form">
        <div class="weight-bold-text">仕入れ先</div>
        <%= form.text_field :supplier, placeholder: "品番" %>
      </div>
  
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<div class="contents">
  <h3>商品</h3>
    <div class="item-lists">
      <% @items.each do |item| %>
        <div class="item-list">
          <div class="item-name">
            <%= link_to item.product_number, item_path(item.id),class:"menuLIST" %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/items/show.html.erb
<div class="contents">
  <div class="container">
    <h3>商品詳細</h3>
    <table >
      <tr>
        <th class="detail-property">商品名</th>
        <td class="detail-index"><%= @item.item_name %></td>
      </tr>
      <tr>
        <th class="detail-property">品番</th>
        <td class="detail-index"><%= @item.product_number %></td>
      </tr>
      <tr>
        <th class="detail-property">定価</th>
        <td class="detail-index"><%= @item.price %></td>
      </tr>
      <tr>
        <th class="detail-property">仕切り</th>
        <td class="detail-index"><%= @item.rate %></td>
      </tr>
      <tr>
        <th class="detail-property">ガス種</th>
        <td class="detail-index"><%= @item.gas.name %></td>
      </tr>
      <tr>
        <th class="detail-property">仕入れ先</th>
        <td class="detail-index"><%= @item.supplier %></td>
      </tr>
    </table>
    <% @item.images.each do |image| %>
      <div class="detail-property">画像</div>
      <div class="detail-index"><%= image_tag image.variant(resize: '400x400'), class: 'item-images' if @item.images.attached? %></div>
    <% end %>

    <div class="delete">
      <%= link_to '削除する', item_path,class:"menuLIST", method: :delete %>
    </div>
    <div class="edit">
      <%= link_to '編集', edit_item_path(@item.id),class:"menuLIST", method: :get %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kousuke</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="header">
        <h1><a href="/">工助</a></h1>
          
      </div>
      <%= yield %>
  </body>
</html>

app/views/properties/edit.html.erb
<div class="contents">
  <div class="container">
    <h3>物件登録</h3>
    <%= form_with(model: @property, local: true) do |form| %>
    <div class="input-form">
      <div class="property-name form">
      <div class="property-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
        <div class="weight-bold-text">物件名</div>
        <%= form.text_field :property_name, placeholder: "物件名" %>
      </div>
      <div class="address form">
        <div class="weight-bold-text">住所</div>
        <%= form.text_field :address, placeholder: "住所" %>
      </div>
      <div class="existing-information form">
        <div class="weight-bold-text">既存情報</div>
        <%= form.text_field :existing_information, placeholder: "既存情報" %>
      </div>
      <div class="new-information form">
        <div class="weight-bold-text">新規機種</div>
        <%= form.text_field :new_information, placeholder: "新規機種" %>
      </div>
      <div class="remarks form">
        <div class="weight-bold-text">備考</div>
        <%= form.text_area :remarks, placeholder: "備考", rows: "10", size: "53x10" %>
      </div>
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/properties/index.html.erb
<div class="menu">
  <ul>
    <li><%= link_to "物件登録", new_property_path, class:"menuLIST" %></li>
    <li><%= link_to "商品検索", items_path, class:"menuLIST" %></li>
    <li><%= link_to "商品登録", new_item_path, class:"menuLIST" %></li>
    <div class="user-list">
    <% if user_signed_in? %>
    <li><%= link_to current_user.name, "#", class: "user-name menuLIST" %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, class:"menuLIST", method: :delete %></li>
    <% else %>
      <li><%= link_to "ログイン", new_user_session_path, class:"menuLIST" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "menuLIST" %></li>
    <% end %>
    </div>
  </ul>
</div>

<div class="contents">

<div class="search">
  <h3>物件を検索する</h3>
  <%= form_with url: search_properties_path, local: true, method: :get do |form| %>
    <%= form.text_field :keyword, placeholder: "物件名" %>
    <%= form.submit "検索" %>
  <% end %>
</div>


  <div class="record-prprerty">
    <h3>登録した物件</h3>
    <div class="property-lists">
        <% @properties.each do |property| %>
          <div class="property-list">
            <%= link_to property.property_name, property_path(property.id), class:"menuLIST" %>
            <%= property.address %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
<div class="contents">
  <div class="container">
    <h3>物件登録</h3>
    <%= form_with(model: @property, local: true) do |form| %>
    <div class="input-form">
      <div class="weight-bold-text">画像</div>
      <div class="property-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
      <div class="property-name form">
        <div class="weight-bold-text">物件名</div>
        <%= form.text_field :property_name, placeholder: "物件名" %>
      </div>
      <div class="address form">
        <div class="weight-bold-text">住所</div>
        <%= form.text_field :address, placeholder: "住所" %>
      </div>
      <div class="kinds form">
        <div class="weight-bold-text">物件情報</div>
        <%= form.collection_select(:property_kind_id, PropertyKind.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="parking form">
        <div class="weight-bold-text">駐車場情報</div>
        <%= form.collection_select(:parking_id, Parking.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="gas form">
        <div class="weight-bold-text">ガス種</div>
        <%= form.collection_select(:gas_id, Gas.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="remarks form">
        <div class="weight-bold-text">備考</div>
        <%= form.text_area :remarks, placeholder: "備考", rows: "10", size: "53x10" %>
      </div>
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/properties/search.html.erb
<div class="contents">
<h3>物件</h3>
  <div class="property-lists">
      <% @properties.each do |property| %>
        <div class="property-list">
          <div class="property-name">
            <%= link_to property.property_name, property_path(property.id), class:"menuLIST" %>
          </div>
          <div class="property-address">
            <%= property.address %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/properties/show.html.erb
<div class="contents">
  <div class="container">
    <h3>物件詳細</h3>
    <table >
      <tr>
        <th class="detail-property">物件名</th>
        <td class="detail-index"><%= @property.property_name %></td>
      </tr>
      <tr>
        <th class="detail-property">住所</th>
        <td class="detail-index"><%= @property.address %></td>
      </tr>
      <tr>
        <th class="detail-property">物件情報</th>
        <td class="detail-index"><%= @property.propertyKind.name %></td>
      </tr>
      <tr>
        <th class="detail-property">駐車場情報</th>
        <td class="detail-index"><%= @property.parking.name %></td>
      </tr>
      <tr>
        <th class="detail-property">ガス種</th>
        <td class="detail-index"><%= @property.gas.name %></td>
      </tr>
      <tr>
        <th class="detail-property">備考</th>
        <td class="detail-index"><%= @property.remarks %></td>
      </tr>
    </table>
    <% @property.images.each do |image| %>
      <div class="detail-property">画像</div>
      <div class="detail-index"><%= image_tag image.variant(resize: '400x400'), class: 'property-images' if @property.images.attached? %></div>
    <% end %>

  <div class="delete">
    <%= link_to '削除する', property_path(@property.id),class:"menuLIST", method: :delete %>
  </div>
  <div class="edit">
    <%= link_to '編集', edit_property_path(@property.id),class:"menuLIST", method: :get %>
  </div>
  <div class="jump-room">
    <%= link_to "部屋情報を登録する", property_rooms_path(@property.id), class:"menuLIST" %>
  </div>

    <div class="rooms">
      <h4>部屋情報一覧</h4>
      <div class="room-lists">
        <% @rooms.each do |room| %>
        <div class="room-list">
          <%= link_to room.room_number, property_room_path(room.property_id, room.id), class:"menuLIST"%>
          <%= room.construction_detail %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="contents">
  <div class="container">
    <h3>部屋情報登録</h3>
    <%= form_with(model: [@property, @room],  local: true) do |form| %>
    <div class="input-form">
      <div class="property-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
      <div class="room_number form">
        <div class="weight-bold-text">部屋番号</div>
        <%= form.text_field :room_number, placeholder: "部屋番号" %>
      </div>
      <div class="construction_detail form">
        <div class="weight-bold-text">工事内容</div>
        <%= form.text_field :construction_detail, placeholder: "工事内容" %>
      </div>
      <div class="instruction form">
        <div class="weight-bold-text">工事指示</div>
        <%= form.text_area :instruction, placeholder: "工事指示", rows: "10", size: "53x10" %>
      </div>
      </div>
      <div class="remarks_room form">
        <div class="weight-bold-text">備考</div>
        <%= form.text_area :remarks_room, placeholder: "備考", rows: "10", size: "53x10" %>
      </div>
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="contents">
  <div class="container">
    <h3>部屋情報登録</h3>
    <%= form_with(model: [@property, @room],  local: true) do |form| %>
    <div class="input-form">
      <div class="property-image">
        <%= form.file_field :images, multiple: true, class:"item-image" %>
      </div>
      <div class="room_number form">
        <div class="weight-bold-text">部屋番号</div>
        <%= form.text_field :room_number, placeholder: "部屋番号" %>
      </div>
      <div class="construction_detail form">
        <div class="weight-bold-text">工事内容</div>
        <%= form.text_field :construction_detail, placeholder: "工事内容" %>
      </div>
      <div class="existing-information form">
        <div class="weight-bold-text">既存情報</div>
        <%= form.text_field :existing_information, placeholder: "既存情報" %>
      </div>
      <div class="existing-maker form">
        <div class="weight-bold-text">既存メーカー</div>
        <%= form.text_field :existing_maker, placeholder: "既存メーカー" %>
      </div>
      <div class="construction-time form">
        <div class="weight-bold-text">工事時間</div>
        <%= form.collection_select(:construction_time_id, ConstructionTime.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="instruction form">
        <div class="weight-bold-text">工事指示</div>
        <%= form.text_area :instruction, placeholder: "工事指示", rows: "10", size: "53x10" %>
      </div>
      </div>
      <div class="remarks_room form">
        <div class="weight-bold-text">備考</div>
        <%= form.text_area :remarks_room, placeholder: "備考", rows: "10", size: "53x10" %>
      </div>
      <div class="construction-day form">
        <div class="weight-bold-text">工事日</div>
        <%= form.text_field :construction_day, placeholder: "工事日" %>
      </div>
      <%= form.submit "登録する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="contents">
<div class="container">
  <h3>部屋情報</h3>
    <table class="detail-table">
      <tr>
        <th class="detail-property">部屋番号</th>
        <td class="detail-index"><%= @room.room_number %></td>
      </tr>
      <tr>
        <th class="detail-property">工事内容</th>
        <td class="detail-index"><%= @room.construction_detail %></td>
      </tr>
      <tr>
        <th class="detail-property">既存情報</th>
        <td class="detail-index"><%= @room.existing_information %></td>
      </tr>
      <tr>
        <th class="detail-property">既存メーカー</th>
        <td class="detail-index"><%= @room.existing_maker%></td>
      </tr>
      <tr>
        <th class="detail-property">工事時間</th>
        <td class="detail-index"><%= @room.construction_time.name %></td>
      </tr>
      <tr>
        <th class="detail-property">工事指示</th>
        <td class="detail-index"><%= @room.instruction %></td>
      </tr>
      <tr>
        <th class="detail-property">備考</th>
        <td class="detail-index"><%= @room.remarks_room %></td>
      </tr>
      <tr>
        <th class="detail-property">工事日</th>
        <td class="detail-index"><%= @room.construction_day %></td>
      </tr>
    </table>

    <% @room.images.each do |image| %>
      <div class="detail-property">画像</div>
      <div class="detail-index"><%= image_tag image.variant(resize: '400x400'), class: 'property-images' if @room.images.attached? %></div>
    <% end %>

  <div class="delete">
    <%= link_to '削除する', property_room_path(@property, @room.id),class:"menuLIST", method: :delete %>
  </div>
  <div class="edit">
    <%= link_to '編集', edit_property_room_path(@property.id, @room.id),class:"menuLIST", method: :get %>
  </div>
  <div class="jump-room">
    <%= link_to "アプローチを登録する", property_room_approaches_path(@property.id, @room.id), class:"menuLIST" %>
  </div>
  <div class="back">
    <%= link_to "物件詳細に戻る", property_path(@property.id), class:"menuLIST" %>
  </div>

    <div class="approaches">
      <h4>アプローチ</h4>
      <div class="approach-lists">
        <% @approach.each do |approach| %>
        <div class="approach-list">
          <div class="record">
            <div class="user-name"><%= approach.user.name %></div>
            <div class="create-day"><%= approach.created_at %></div>
          </div>
          <div class="approach-content"><%= approach.content %></div>
          <div class="delele-approach">
            <%= link_to '削除する',  property_room_approach_path(@property.id, @room.id, approach.id), class:"menuLIST", method: :delete %>
          </div>
        </div>
        <% end %>
    </div>
    </div>

  </div>
</div>